### ISSUE TITLE
Adicionar gunicorn ao projeto

### ISSUE THREAD

**Issue by jocsakesley** [jocsakesley/raizama#32]
Adicionar gunicorn nas dependências para uso em produção

**Comment by cuducos** [comment]
Acredito que o Gunicorn **já** esteja no projeto, tanto no [`requirements.txt`](https://github.com/jocsakesley/raizama/blob/a8bcedf7b3ec339065107b8466a5fd8e1913f348/requirements.txt#L36) quanto no [`ptpoetry.toml`](https://github.com/jocsakesley/raizama/blob/a8bcedf7b3ec339065107b8466a5fd8e1913f348/pyproject.toml#L17). Pode explicar melhor o contexto dessa _issue_?
